title: LeVioc
baseline: Site Web en mémoire de LeVioc.
baseurl: https://levioc.netlify.app/
description: Site Web en mémoire de LeVioc, meilleur partenaire de jeu vidéo.
author:
    name: Arnaud Ligny
    url: https://arnaudligny.fr
image: avatar.jpg
