title: Les évaluations de LeVioc
baseurl: https://levioc.netlify.app/
description: Ce site web liste les évaluations de jeux vidéos rédigées par LeVioc sur Steam.
author:
    name: Arnaud Ligny
    url: https://arnaudligny.fr
image: avatar.jpg
language: fr
languages:
  - code: fr
    name: Français
    locale: fr_FR
